export default [
    'Rock',
    'Pop music',
    'Popular music',
    'Rhythm and blues',
    'Classical music',
    'Country music',
    'Hip hop music',
    'Jazz',
    'Blues',
    'Folk music',
    'Electronic music',
    'Electronic dance music',
    'Heavy metal',
    'Alternative rock',
    'Soul music',
    'Dance music',
    'Singing',
    'Indie rock',
    'Latin music',
    'Pop rock',
    'Funk',
    'Punk rock',
    'Musical theatre',
    'Reggae',
    'Easy listening',
    'New-age music',
    'Techno',
    'Vocal music',
    'Dubstep',
    'Experimental music',
    'House music',
    'Psychedelic rock',
    'Ambient music',
    'World music',
    'Disco',
    'Industrial music',
    'Grunge',
    'Instrumental',
    'Electro',
    'Trance music',
    'Avant-garde',
    'New wave',
    'Rapping',
    'Contemporary R\'B',
    'Ska',
    'Progressive rock',
    'Gospel music',
    'Adult contemporary music',
    'J-pop',
    'Opera',
    'Hardcore punk',
];